/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/capture/new`; params?: Router.UnknownInputParams; } | { pathname: `/space/add`; params?: Router.UnknownInputParams; } | { pathname: `/space`; params?: Router.UnknownInputParams; } | { pathname: `/space/log`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/chat`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/explore`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/space/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/space/log/[logId]`, params: Router.UnknownInputParams & { logId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/capture/new`; params?: Router.UnknownOutputParams; } | { pathname: `/space/add`; params?: Router.UnknownOutputParams; } | { pathname: `/space`; params?: Router.UnknownOutputParams; } | { pathname: `/space/log`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/space/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/space/log/[logId]`, params: Router.UnknownOutputParams & { logId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/capture/new${`?${string}` | `#${string}` | ''}` | `/space/add${`?${string}` | `#${string}` | ''}` | `/space${`?${string}` | `#${string}` | ''}` | `/space/log${`?${string}` | `#${string}` | ''}` | `/tabs/chat${`?${string}` | `#${string}` | ''}` | `/tabs/explore${`?${string}` | `#${string}` | ''}` | `/tabs${`?${string}` | `#${string}` | ''}` | `/tabs/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/capture/new`; params?: Router.UnknownInputParams; } | { pathname: `/space/add`; params?: Router.UnknownInputParams; } | { pathname: `/space`; params?: Router.UnknownInputParams; } | { pathname: `/space/log`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/chat`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/explore`; params?: Router.UnknownInputParams; } | { pathname: `/tabs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; } | `/+not-found` | `/space/${Router.SingleRoutePart<T>}` | `/space/log/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/space/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/space/log/[logId]`, params: Router.UnknownInputParams & { logId: string | number; } };
    }
  }
}
